# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 02:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('answer', models.CharField(max_length=255)),
                ('explanation', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
